name: Code Inspector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    name: Check code format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -V
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Run isort
        run: poetry run isort --check --diff *
      - name: Run black
        run: poetry run black --check --diff --color .
      - name: Run flake8
        run: peotry run flake8