name: Code Inspector

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-format:
    name: Check code format

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -V
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Run isort
        run: poetry run isort --check --diff ninja_apikey sample_project
      - name: Run black
        run: poetry run black --check --diff --color .
      - name: Run flake8
        run: poetry run flake8

  run-pytest:
    name: Run pytest

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6.7,3.7,3.8,3.9]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -V
      - name: Install poetry
        run: python -m pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Run pytest
        run: poetry run pytest -v sample_project ninja_apikey