name: Deploy release

on:
  relase:
    types: [published]

jobs:
  publish:
    name: Publish to PyPI

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Display Python version
        run: python -V
      - name: Install poetry
        run: python -m pip install poetry
      - name: Build and publish package
        run: poetry publish --build -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}